#!/bin/bash

AUDIO_HIGH_SYMBOL=${AUDIO_HIGH_SYMBOL:-'  '}

AUDIO_MED_THRESH=${AUDIO_MED_THRESH:-50}
AUDIO_MED_SYMBOL=${AUDIO_MED_SYMBOL:-' '}

AUDIO_LOW_THRESH=${AUDIO_LOW_THRESH:-0}
AUDIO_LOW_SYMBOL=${AUDIO_LOW_SYMBOL:-' '}

AUDIO_MUTED_SYMBOL=${AUDIO_MED_SYMBOL:-' '}

DEFAULT_COLOR=${DEFAULT_COLOR:-"#ffffff"}
MUTED_COLOR=${MUTED_COLOR:-"#b11226"}

SINK=$(pactl get-default-sink)
VOLUME=$(pactl get-sink-volume "$SINK" | grep -oP '\d+(?=%)' | head -n1)
MUTED=$(pactl get-sink-mute "$SINK" | grep -oP 'yes|no')

if [[ "$MUTED" == "yes" ]] ; then
    echo "${AUDIO_MUTED_SYMBOL}: Mute"
    echo "${AUDIO_MUTED_SYMBOL}"
    echo "#b11226"
else
    echo "${AUDIO_HIGH_SYMBOL} : ${VOLUME}%"
    echo "${VOLUME}%"
fi
